///**
// * 
// */
//package eu.riscoss.datacollector;
//
//import java.io.IOException;
//import java.io.PrintStream;
//import java.util.ArrayList;
//import java.util.List;
//import java.util.Properties;
//
//import eu.riscoss.datacollector.common.IndicatorsMap;
//import eu.riscoss.dataproviders.RDR;
//import eu.riscoss.dataproviders.RdpConfig;
//import eu.riscoss.dataproviders.RiskData;
//
//
///**
// * @author mirko
// *
// */
//public abstract class DataProvider implements AbstractDataProvider {
//
//	
//	public static void run(AbstractDataProvider provider, String[] args) {
//		final String defaultPropertiesFile = "default.properties";
//		Properties properties;
//		
//		if (args.length==0){ //some default values for testing
//			String[] s = new String[4];
//			s[0] = "-rdr";
//			//		s[1] = "http://riscoss-platform.devxwiki.com/rdr"; //M24 RDR
//			//		s[1] = "http://riscossplatform.ow2.org:8080/riscoss-rdr"; //OW2instance RDR
//			s[1] = "http://151.80.95.66:8080/riscoss-rdr"; //OW2instance RDR
//			s[2] = "-properties";
//			String component = "XWiki";
//			s[3] = "Riscossconfig_"+component+".properties";
//			args = s;
//		}
//		//exec_single(s);
//
//		//read the default config file
//		Properties defaultProperties = RdpConfig.loadDefaults(defaultPropertiesFile);
//		//read the config from file
//		properties = RdpConfig.load(args[3], defaultProperties);
//		
//		IndicatorsMap im = new IndicatorsMap(properties.getProperty("targetEntity"));
//		
//		try {
//			//redirecting all stdout to stderr
//			PrintStream stdout = System.out;
//			System.setOut(System.err);
//			provider.createIndicators(im, properties);
//			System.setOut(stdout);
//
//			List<RiskData> riskData = new ArrayList<RiskData>(); /* This list should be generated by the Risk Data Collector logic :) */
//			riskData.addAll(im.values());
//			System.out.println(RDR.getRiskDataJson(riskData).toString());
//
//		} catch (IOException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} catch (Exception e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//		
//
//	}
//	
//	/* (non-Javadoc)
//	 * @see eu.riscoss.dataproviders.common.AbstractDataProvider#createIndicators(eu.riscoss.dataproviders.common.IndicatorsMap, java.util.Properties)
//	 */
//	@Override
//	public abstract void createIndicators(IndicatorsMap im, Properties properties) throws Exception;
//}
